var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "yyyyddMM",
            "fulldayshow": "yyyy d L",
            "fulldayvalue": "yyyydM",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "周日",
            "mon": "周一",
            "tue": "周二",
            "wed": "周三",
            "thu": "周四",
            "fri": "周五",
            "sat": "周六",
            "jan": "一月",
            "feb": "二月",
            "mar": "三月",
            "apr": "四月",
            "may": "五月",
            "jun": "六月",
            "jul": "七月",
            "aug": "八月",
            "sep": "九月",
            "oct": "十月",
            "nov": "十一月",
            "dec": "十二月"
        },
        "no_implemented": "尚未实施",
        "to_date_view": "点击当前日期的视图",
        "i_undefined": "未定义",
        "allday_event": "全天事件",
        "repeat_event": "重复事件",
        "time": "时间",
        "event": "事件",
        "location": "位置",
        "participant": "参加者",
        "get_data_exception": "Exception when getting data",
        "new_event": "New event",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "事件标题不能为空或包含（$<>）",
        "view_no_ready": "View is not ready",
        "example": "e.g., meeting at room 107",
        "content": "What",
        "create_event": "Create event",
        "update_detail": "Edit details",
        "click_to_detail": "View details",
        "i_delete": "Delete",
        "day_plural": "days",
        "others": "Others",
        "item": ""
    }
});
