var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dim",
            "mon": "lun",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Jeu",
            "fri": "Ven",
            "sat": "Sam",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Juin",
            "jul": "Juil",
            "aug": "Aou",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "Pas encore mis en œuvre",
        "to_date_view": "Cliquez à la vue de la date actuelle",
        "i_undefined": "Indéfini",
        "allday_event": "Toute la journée",
        "repeat_event": "Récurrence",
        "time": "Date",
        "event": "Event",
        "location": "Lieu",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "Nouvel évènement",
        "confirm_delete_event": "Confirmez-vous supprimer cet événement? ",
        "confrim_delete_event_or_all": "Voulez-vous à tous les événements de répétition ou seulement cet événement? \r\nCliquez [OK] à supprimer suelement cet événement, cliquez [Cancel] à supprimer tous les événements",
        "data_format_error": "Data format error! ",
        "invalid_title": "Le nom d'événement ne peut pas être vide ou contenir ($<>)",
        "view_no_ready": "View n'est pas prêt",
        "example": "e.g., à salle 101",
        "content": "Événement",
        "create_event": "Créer",
        "update_detail": "Modifier l'événement",
        "click_to_detail": "Voir l'événement",
        "i_delete": "Supprimer",
        "day_plural": "Jours",
        "others": "Autres",
        "item": ""
    }
});
