//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.MyClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS_Message", Namespace="http://microsoft.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class SMS_Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int sms_idField;
        
        private int grp_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sms_telnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sms_subjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sms_contentField;
        
        private bool sms_sendField;
        
        private int usr_idField;
        
        private System.DateTime sms_d_creationField;
        
        private System.Nullable<System.DateTime> sms_d_sendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sms_signatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sms_appGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sms_id {
            get {
                return this.sms_idField;
            }
            set {
                if ((this.sms_idField.Equals(value) != true)) {
                    this.sms_idField = value;
                    this.RaisePropertyChanged("sms_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int grp_id {
            get {
                return this.grp_idField;
            }
            set {
                if ((this.grp_idField.Equals(value) != true)) {
                    this.grp_idField = value;
                    this.RaisePropertyChanged("grp_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sms_telnumber {
            get {
                return this.sms_telnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.sms_telnumberField, value) != true)) {
                    this.sms_telnumberField = value;
                    this.RaisePropertyChanged("sms_telnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sms_subject {
            get {
                return this.sms_subjectField;
            }
            set {
                if ((object.ReferenceEquals(this.sms_subjectField, value) != true)) {
                    this.sms_subjectField = value;
                    this.RaisePropertyChanged("sms_subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sms_content {
            get {
                return this.sms_contentField;
            }
            set {
                if ((object.ReferenceEquals(this.sms_contentField, value) != true)) {
                    this.sms_contentField = value;
                    this.RaisePropertyChanged("sms_content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool sms_send {
            get {
                return this.sms_sendField;
            }
            set {
                if ((this.sms_sendField.Equals(value) != true)) {
                    this.sms_sendField = value;
                    this.RaisePropertyChanged("sms_send");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int usr_id {
            get {
                return this.usr_idField;
            }
            set {
                if ((this.usr_idField.Equals(value) != true)) {
                    this.usr_idField = value;
                    this.RaisePropertyChanged("usr_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime sms_d_creation {
            get {
                return this.sms_d_creationField;
            }
            set {
                if ((this.sms_d_creationField.Equals(value) != true)) {
                    this.sms_d_creationField = value;
                    this.RaisePropertyChanged("sms_d_creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> sms_d_send {
            get {
                return this.sms_d_sendField;
            }
            set {
                if ((this.sms_d_sendField.Equals(value) != true)) {
                    this.sms_d_sendField = value;
                    this.RaisePropertyChanged("sms_d_send");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sms_signature {
            get {
                return this.sms_signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.sms_signatureField, value) != true)) {
                    this.sms_signatureField = value;
                    this.RaisePropertyChanged("sms_signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string sms_appGuid {
            get {
                return this.sms_appGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.sms_appGuidField, value) != true)) {
                    this.sms_appGuidField = value;
                    this.RaisePropertyChanged("sms_appGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="MyClientService.MyClientWebServicesSoap")]
    public interface MyClientWebServicesSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://microsoft.com/webservices/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/HelloWorld", ReplyAction="*")]
        ERP.Web.MyClientService.HelloWorldResponse HelloWorld(ERP.Web.MyClientService.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément token de l'espace de noms http://microsoft.com/webservices/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetMessageSetErrorMessage", ReplyAction="*")]
        ERP.Web.MyClientService.GetMessageSetErrorMessageResponse GetMessageSetErrorMessage(ERP.Web.MyClientService.GetMessageSetErrorMessageRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément aMessage de l'espace de noms http://microsoft.com/webservices/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/AddMessage", ReplyAction="*")]
        ERP.Web.MyClientService.AddMessageResponse AddMessage(ERP.Web.MyClientService.AddMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://microsoft.com/webservices/", Order=0)]
        public ERP.Web.MyClientService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ERP.Web.MyClientService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public ERP.Web.MyClientService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ERP.Web.MyClientService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageSetErrorMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageSetErrorMessage", Namespace="http://microsoft.com/webservices/", Order=0)]
        public ERP.Web.MyClientService.GetMessageSetErrorMessageRequestBody Body;
        
        public GetMessageSetErrorMessageRequest() {
        }
        
        public GetMessageSetErrorMessageRequest(ERP.Web.MyClientService.GetMessageSetErrorMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GetMessageSetErrorMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetMessageSetErrorMessageRequestBody() {
        }
        
        public GetMessageSetErrorMessageRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageSetErrorMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageSetErrorMessageResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public ERP.Web.MyClientService.GetMessageSetErrorMessageResponseBody Body;
        
        public GetMessageSetErrorMessageResponse() {
        }
        
        public GetMessageSetErrorMessageResponse(ERP.Web.MyClientService.GetMessageSetErrorMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GetMessageSetErrorMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP.Web.MyClientService.SMS_Message[] GetMessageSetErrorMessageResult;
        
        public GetMessageSetErrorMessageResponseBody() {
        }
        
        public GetMessageSetErrorMessageResponseBody(ERP.Web.MyClientService.SMS_Message[] GetMessageSetErrorMessageResult) {
            this.GetMessageSetErrorMessageResult = GetMessageSetErrorMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMessage", Namespace="http://microsoft.com/webservices/", Order=0)]
        public ERP.Web.MyClientService.AddMessageRequestBody Body;
        
        public AddMessageRequest() {
        }
        
        public AddMessageRequest(ERP.Web.MyClientService.AddMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class AddMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP.Web.MyClientService.SMS_Message aMessage;
        
        public AddMessageRequestBody() {
        }
        
        public AddMessageRequestBody(ERP.Web.MyClientService.SMS_Message aMessage) {
            this.aMessage = aMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMessageResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public ERP.Web.MyClientService.AddMessageResponseBody Body;
        
        public AddMessageResponse() {
        }
        
        public AddMessageResponse(ERP.Web.MyClientService.AddMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddMessageResponseBody {
        
        public AddMessageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyClientWebServicesSoapChannel : ERP.Web.MyClientService.MyClientWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyClientWebServicesSoapClient : System.ServiceModel.ClientBase<ERP.Web.MyClientService.MyClientWebServicesSoap>, ERP.Web.MyClientService.MyClientWebServicesSoap {
        
        public MyClientWebServicesSoapClient() {
        }
        
        public MyClientWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyClientWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyClientWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyClientWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP.Web.MyClientService.HelloWorldResponse ERP.Web.MyClientService.MyClientWebServicesSoap.HelloWorld(ERP.Web.MyClientService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ERP.Web.MyClientService.HelloWorldRequest inValue = new ERP.Web.MyClientService.HelloWorldRequest();
            inValue.Body = new ERP.Web.MyClientService.HelloWorldRequestBody();
            ERP.Web.MyClientService.HelloWorldResponse retVal = ((ERP.Web.MyClientService.MyClientWebServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP.Web.MyClientService.GetMessageSetErrorMessageResponse ERP.Web.MyClientService.MyClientWebServicesSoap.GetMessageSetErrorMessage(ERP.Web.MyClientService.GetMessageSetErrorMessageRequest request) {
            return base.Channel.GetMessageSetErrorMessage(request);
        }
        
        public ERP.Web.MyClientService.SMS_Message[] GetMessageSetErrorMessage(string token) {
            ERP.Web.MyClientService.GetMessageSetErrorMessageRequest inValue = new ERP.Web.MyClientService.GetMessageSetErrorMessageRequest();
            inValue.Body = new ERP.Web.MyClientService.GetMessageSetErrorMessageRequestBody();
            inValue.Body.token = token;
            ERP.Web.MyClientService.GetMessageSetErrorMessageResponse retVal = ((ERP.Web.MyClientService.MyClientWebServicesSoap)(this)).GetMessageSetErrorMessage(inValue);
            return retVal.Body.GetMessageSetErrorMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP.Web.MyClientService.AddMessageResponse ERP.Web.MyClientService.MyClientWebServicesSoap.AddMessage(ERP.Web.MyClientService.AddMessageRequest request) {
            return base.Channel.AddMessage(request);
        }
        
        public void AddMessage(ERP.Web.MyClientService.SMS_Message aMessage) {
            ERP.Web.MyClientService.AddMessageRequest inValue = new ERP.Web.MyClientService.AddMessageRequest();
            inValue.Body = new ERP.Web.MyClientService.AddMessageRequestBody();
            inValue.Body.aMessage = aMessage;
            ERP.Web.MyClientService.AddMessageResponse retVal = ((ERP.Web.MyClientService.MyClientWebServicesSoap)(this)).AddMessage(inValue);
        }
    }
}
