import { useMemo, useState } from 'react'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useTranslation } from 'react-i18next'
import { PageContainer } from '@/components/ui/layout/PageContainer'
import { PageHeader } from '@/components/ui/layout/PageHeader'
import { Card, CardContent, CardHeader } from '@/components/ui/layout/Card'
import { useOrders, useOrder } from '@/hooks/useOrders'
import { useCarriers } from '@/hooks/useLogistics'

export const Route = createFileRoute('/_authenticated/deliveries/new')({
  validateSearch: (search) => {
    const orderId =
      typeof search.orderId === 'string'
        ? Number(search.orderId)
        : typeof search.orderId === 'number'
          ? search.orderId
          : undefined
    return {
      orderId: Number.isFinite(orderId) ? orderId : undefined,
    }
  },
  component: NewDeliveryPage,
})

function NewDeliveryPage() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { orderId: initialOrderId } = Route.useSearch()
  const [selectedOrderId, setSelectedOrderId] = useState<number | ''>(initialOrderId ?? '')

  const { data: ordersData, isLoading: ordersLoading } = useOrders({
    page: 1,
    pageSize: 50,
    sortBy: 'cod_d_creation',
    sortOrder: 'desc',
  })
  const { data: orderDetail, isLoading: orderLoading } = useOrder(
    typeof selectedOrderId === 'number' ? selectedOrderId : 0
  )
  const { data: carriers = [] } = useCarriers(true)

  const orderOptions = useMemo(() => ordersData?.data || [], [ordersData])

  const handleOrderChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const value = event.target.value
    setSelectedOrderId(value ? Number(value) : '')
  }

  const actions = (
    <div className="flex gap-2">
      <button onClick={() => navigate({ to: '/deliveries' as any })} className="btn-secondary">
        {t('common.cancel')}
      </button>
      <button className="btn-primary" disabled>
        {t('common.save')}
      </button>
    </div>
  )

  return (
    <PageContainer>
      <PageHeader
        title={t('deliveries.newDelivery')}
        description={t('deliveries.manageDescription')}
        actions={actions}
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader title={t('deliveries.deliveryDetails')} />
            <CardContent>
              <form className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.reference')}</label>
                    <input type="text" className="input w-full" placeholder={t('common.autoGenerated', { defaultValue: 'Auto-generated' })} disabled />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.order')} *</label>
                    <select
                      className="input w-full"
                      value={selectedOrderId}
                      onChange={handleOrderChange}
                    >
                      <option value="">{ordersLoading ? t('common.loading') : t('orders.selectOrder', { defaultValue: 'Select an order...' })}</option>
                      {orderOptions.map((order) => (
                        <option key={order.id} value={order.id}>
                          {order.reference}{order.clientName ? ` — ${order.clientName}` : ''}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.expectedDate')} *</label>
                    <input type="date" className="input w-full" defaultValue={new Date().toISOString().split('T')[0]} />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.carrier')}</label>
                    <select className="input w-full">
                      <option value="">{t('logistics.selectCarrier', { defaultValue: 'Select a carrier...' })}</option>
                      {carriers.map((carrier) => (
                        <option key={carrier.car_id} value={carrier.car_id}>
                          {carrier.car_name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.trackingNumber')}</label>
                    <input type="text" className="input w-full" placeholder={t('deliveries.trackingNumber')} />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.packages')}</label>
                    <input type="number" className="input w-full" placeholder="1" min="1" />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.weight')} (kg)</label>
                    <input type="number" className="input w-full" placeholder="0.00" step="0.01" min="0" />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.shippingAddress')}</label>
                  <textarea className="input w-full" rows={3} placeholder={t('common.address')} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-1">{t('deliveries.notes')}</label>
                  <textarea className="input w-full" rows={2} placeholder={t('deliveries.notes')} />
                </div>
              </form>
            </CardContent>
          </Card>

          <Card>
            <CardHeader title={t('deliveries.items')} />
            <CardContent>
              <table className="w-full">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-2 text-sm text-muted-foreground">{t('orders.product')}</th>
                    <th className="text-right py-2 text-sm text-muted-foreground">{t('orders.quantity')}</th>
                    <th className="text-right py-2 text-sm text-muted-foreground">{t('orders.delivered')}</th>
                    <th className="text-right py-2 text-sm text-muted-foreground">{t('deliveries.toDeliver', { defaultValue: 'To Deliver' })}</th>
                  </tr>
                </thead>
                <tbody>
                  {orderLoading && (
                    <tr>
                      <td colSpan={4} className="text-center py-8 text-muted-foreground">
                        {t('common.loading')}
                      </td>
                    </tr>
                  )}
                  {!orderLoading && orderDetail?.lines?.length ? (
                    orderDetail.lines.map((line: any) => {
                      const ordered = Number(line.quantity || 0)
                      const delivered = Number(line.deliveredQuantity || 0)
                      const toDeliver = Math.max(ordered - delivered, 0)
                      return (
                        <tr key={line.id} className="border-b">
                          <td className="py-3">
                            <p className="font-medium">{line.productName || line.description || '-'}</p>
                            {line.productReference && (
                              <p className="text-sm text-muted-foreground font-mono">{line.productReference}</p>
                            )}
                          </td>
                          <td className="text-right py-3">{ordered}</td>
                          <td className="text-right py-3">{delivered}</td>
                          <td className="text-right py-3 font-medium">{toDeliver}</td>
                        </tr>
                      )
                    })
                  ) : (
                    <tr>
                      <td colSpan={4} className="text-center py-8 text-muted-foreground">
                        {selectedOrderId ? t('orders.noLineItems', { defaultValue: 'No line items' }) : t('orders.selectOrder', { defaultValue: 'Select an order to see items to deliver.' })}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader title={t('common.status')} />
            <CardContent>
              <select className="input w-full">
                <option value="preparing">{t('deliveries.preparing')}</option>
                <option value="ready">{t('deliveries.inTransit', { defaultValue: 'Ready to Ship' })}</option>
                <option value="shipped">{t('deliveries.shipped')}</option>
              </select>
            </CardContent>
          </Card>

          {orderDetail && (
            <Card>
              <CardHeader title={t('orders.title')} />
              <CardContent className="space-y-2">
                <div>
                  <p className="text-sm text-muted-foreground">{t('orders.reference')}</p>
                  <p className="font-mono">{orderDetail.reference}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">{t('orders.client')}</p>
                  <p className="font-medium">{orderDetail.clientName || '-'}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">{t('orders.expectedDelivery')}</p>
                  <p>{orderDetail.expectedDeliveryDate ? new Date(orderDetail.expectedDeliveryDate).toLocaleDateString() : '-'}</p>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </PageContainer>
  )
}
