/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWarehouseIndexRouteImport } from './routes/_authenticated/warehouse/index'
import { Route as AuthenticatedSupplyLotsIndexRouteImport } from './routes/_authenticated/supply-lots/index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedSupplierOrdersIndexRouteImport } from './routes/_authenticated/supplier-orders/index'
import { Route as AuthenticatedSupplierInvoicesIndexRouteImport } from './routes/_authenticated/supplier-invoices/index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes/index'
import { Route as AuthenticatedPurchaseIntentsIndexRouteImport } from './routes/_authenticated/purchase-intents/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedLogisticsIndexRouteImport } from './routes/_authenticated/logistics/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedDriveIndexRouteImport } from './routes/_authenticated/drive/index'
import { Route as AuthenticatedDeliveriesIndexRouteImport } from './routes/_authenticated/deliveries/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedConsigneesIndexRouteImport } from './routes/_authenticated/consignees/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar/index'
import { Route as AuthenticatedBrandsIndexRouteImport } from './routes/_authenticated/brands/index'
import { Route as AuthenticatedSupplyLotsLotIdRouteImport } from './routes/_authenticated/supply-lots/$lotId'
import { Route as AuthenticatedSuppliersSupplierIdRouteImport } from './routes/_authenticated/suppliers/$supplierId'
import { Route as AuthenticatedSupplierOrdersNewRouteImport } from './routes/_authenticated/supplier-orders/new'
import { Route as AuthenticatedSupplierOrdersOrderIdRouteImport } from './routes/_authenticated/supplier-orders/$orderId'
import { Route as AuthenticatedSupplierInvoicesNewRouteImport } from './routes/_authenticated/supplier-invoices/new'
import { Route as AuthenticatedSupplierInvoicesInvoiceIdRouteImport } from './routes/_authenticated/supplier-invoices/$invoiceId'
import { Route as AuthenticatedSettingsEmailLogsRouteImport } from './routes/_authenticated/settings/email-logs'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes/new'
import { Route as AuthenticatedQuotesQuoteIdRouteImport } from './routes/_authenticated/quotes/$quoteId'
import { Route as AuthenticatedPurchaseIntentsIntentIdRouteImport } from './routes/_authenticated/purchase-intents/$intentId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedOrdersNewRouteImport } from './routes/_authenticated/orders/new'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders/$orderId'
import { Route as AuthenticatedLogisticsNewRouteImport } from './routes/_authenticated/logistics/new'
import { Route as AuthenticatedLogisticsShipmentIdRouteImport } from './routes/_authenticated/logistics/$shipmentId'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices/$invoiceId'
import { Route as AuthenticatedDeliveriesNewRouteImport } from './routes/_authenticated/deliveries/new'
import { Route as AuthenticatedDeliveriesDeliveryIdRouteImport } from './routes/_authenticated/deliveries/$deliveryId'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId'
import { Route as AuthenticatedWarehouseMovementsIndexRouteImport } from './routes/_authenticated/warehouse/movements/index'
import { Route as AuthenticatedSettingsUsersIndexRouteImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsImportIndexRouteImport } from './routes/_authenticated/settings/import/index'
import { Route as AuthenticatedIntegrationsShopifyIndexRouteImport } from './routes/_authenticated/integrations/shopify/index'
import { Route as AuthenticatedAccountingStatementsIndexRouteImport } from './routes/_authenticated/accounting/statements/index'
import { Route as AuthenticatedAccountingReceivablesIndexRouteImport } from './routes/_authenticated/accounting/receivables/index'
import { Route as AuthenticatedAccountingPaymentsIndexRouteImport } from './routes/_authenticated/accounting/payments/index'
import { Route as AuthenticatedAccountingExportIndexRouteImport } from './routes/_authenticated/accounting/export/index'
import { Route as AuthenticatedAccountingAgingIndexRouteImport } from './routes/_authenticated/accounting/aging/index'
import { Route as AuthenticatedWarehouseMovementsNewRouteImport } from './routes/_authenticated/warehouse/movements/new'
import { Route as AuthenticatedWarehouseMovementsMovementIdRouteImport } from './routes/_authenticated/warehouse/movements/$movementId'
import { Route as AuthenticatedSettingsUsersNewRouteImport } from './routes/_authenticated/settings/users/new'
import { Route as AuthenticatedSettingsUsersUserIdRouteImport } from './routes/_authenticated/settings/users/$userId'
import { Route as AuthenticatedIntegrationsX3MappingsRouteImport } from './routes/_authenticated/integrations/x3/mappings'
import { Route as AuthenticatedIntegrationsShopifyStoreIdRouteImport } from './routes/_authenticated/integrations/shopify/$storeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWarehouseIndexRoute =
  AuthenticatedWarehouseIndexRouteImport.update({
    id: '/warehouse/',
    path: '/warehouse/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplyLotsIndexRoute =
  AuthenticatedSupplyLotsIndexRouteImport.update({
    id: '/supply-lots/',
    path: '/supply-lots/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierOrdersIndexRoute =
  AuthenticatedSupplierOrdersIndexRouteImport.update({
    id: '/supplier-orders/',
    path: '/supplier-orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierInvoicesIndexRoute =
  AuthenticatedSupplierInvoicesIndexRouteImport.update({
    id: '/supplier-invoices/',
    path: '/supplier-invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchaseIntentsIndexRoute =
  AuthenticatedPurchaseIntentsIndexRouteImport.update({
    id: '/purchase-intents/',
    path: '/purchase-intents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogisticsIndexRoute =
  AuthenticatedLogisticsIndexRouteImport.update({
    id: '/logistics/',
    path: '/logistics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDriveIndexRoute = AuthenticatedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveriesIndexRoute =
  AuthenticatedDeliveriesIndexRouteImport.update({
    id: '/deliveries/',
    path: '/deliveries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsigneesIndexRoute =
  AuthenticatedConsigneesIndexRouteImport.update({
    id: '/consignees/',
    path: '/consignees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBrandsIndexRoute =
  AuthenticatedBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplyLotsLotIdRoute =
  AuthenticatedSupplyLotsLotIdRouteImport.update({
    id: '/supply-lots/$lotId',
    path: '/supply-lots/$lotId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdRoute =
  AuthenticatedSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierOrdersNewRoute =
  AuthenticatedSupplierOrdersNewRouteImport.update({
    id: '/supplier-orders/new',
    path: '/supplier-orders/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierOrdersOrderIdRoute =
  AuthenticatedSupplierOrdersOrderIdRouteImport.update({
    id: '/supplier-orders/$orderId',
    path: '/supplier-orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierInvoicesNewRoute =
  AuthenticatedSupplierInvoicesNewRouteImport.update({
    id: '/supplier-invoices/new',
    path: '/supplier-invoices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierInvoicesInvoiceIdRoute =
  AuthenticatedSupplierInvoicesInvoiceIdRouteImport.update({
    id: '/supplier-invoices/$invoiceId',
    path: '/supplier-invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsEmailLogsRoute =
  AuthenticatedSettingsEmailLogsRouteImport.update({
    id: '/settings/email-logs',
    path: '/settings/email-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotesQuoteIdRoute =
  AuthenticatedQuotesQuoteIdRouteImport.update({
    id: '/quotes/$quoteId',
    path: '/quotes/$quoteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchaseIntentsIntentIdRoute =
  AuthenticatedPurchaseIntentsIntentIdRouteImport.update({
    id: '/purchase-intents/$intentId',
    path: '/purchase-intents/$intentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersNewRoute = AuthenticatedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogisticsNewRoute =
  AuthenticatedLogisticsNewRouteImport.update({
    id: '/logistics/new',
    path: '/logistics/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogisticsShipmentIdRoute =
  AuthenticatedLogisticsShipmentIdRouteImport.update({
    id: '/logistics/$shipmentId',
    path: '/logistics/$shipmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeliveriesNewRoute =
  AuthenticatedDeliveriesNewRouteImport.update({
    id: '/deliveries/new',
    path: '/deliveries/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeliveriesDeliveryIdRoute =
  AuthenticatedDeliveriesDeliveryIdRouteImport.update({
    id: '/deliveries/$deliveryId',
    path: '/deliveries/$deliveryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseMovementsIndexRoute =
  AuthenticatedWarehouseMovementsIndexRouteImport.update({
    id: '/warehouse/movements/',
    path: '/warehouse/movements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexRouteImport.update({
    id: '/settings/users/',
    path: '/settings/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsImportIndexRoute =
  AuthenticatedSettingsImportIndexRouteImport.update({
    id: '/settings/import/',
    path: '/settings/import/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsShopifyIndexRoute =
  AuthenticatedIntegrationsShopifyIndexRouteImport.update({
    id: '/integrations/shopify/',
    path: '/integrations/shopify/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingStatementsIndexRoute =
  AuthenticatedAccountingStatementsIndexRouteImport.update({
    id: '/accounting/statements/',
    path: '/accounting/statements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingReceivablesIndexRoute =
  AuthenticatedAccountingReceivablesIndexRouteImport.update({
    id: '/accounting/receivables/',
    path: '/accounting/receivables/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingPaymentsIndexRoute =
  AuthenticatedAccountingPaymentsIndexRouteImport.update({
    id: '/accounting/payments/',
    path: '/accounting/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingExportIndexRoute =
  AuthenticatedAccountingExportIndexRouteImport.update({
    id: '/accounting/export/',
    path: '/accounting/export/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingAgingIndexRoute =
  AuthenticatedAccountingAgingIndexRouteImport.update({
    id: '/accounting/aging/',
    path: '/accounting/aging/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseMovementsNewRoute =
  AuthenticatedWarehouseMovementsNewRouteImport.update({
    id: '/warehouse/movements/new',
    path: '/warehouse/movements/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWarehouseMovementsMovementIdRoute =
  AuthenticatedWarehouseMovementsMovementIdRouteImport.update({
    id: '/warehouse/movements/$movementId',
    path: '/warehouse/movements/$movementId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersNewRoute =
  AuthenticatedSettingsUsersNewRouteImport.update({
    id: '/settings/users/new',
    path: '/settings/users/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersUserIdRoute =
  AuthenticatedSettingsUsersUserIdRouteImport.update({
    id: '/settings/users/$userId',
    path: '/settings/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsX3MappingsRoute =
  AuthenticatedIntegrationsX3MappingsRouteImport.update({
    id: '/integrations/x3/mappings',
    path: '/integrations/x3/mappings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsShopifyStoreIdRoute =
  AuthenticatedIntegrationsShopifyStoreIdRouteImport.update({
    id: '/integrations/shopify/$storeId',
    path: '/integrations/shopify/$storeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/deliveries/$deliveryId': typeof AuthenticatedDeliveriesDeliveryIdRoute
  '/deliveries/new': typeof AuthenticatedDeliveriesNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/logistics/$shipmentId': typeof AuthenticatedLogisticsShipmentIdRoute
  '/logistics/new': typeof AuthenticatedLogisticsNewRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/purchase-intents/$intentId': typeof AuthenticatedPurchaseIntentsIntentIdRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/settings/email-logs': typeof AuthenticatedSettingsEmailLogsRoute
  '/supplier-invoices/$invoiceId': typeof AuthenticatedSupplierInvoicesInvoiceIdRoute
  '/supplier-invoices/new': typeof AuthenticatedSupplierInvoicesNewRoute
  '/supplier-orders/$orderId': typeof AuthenticatedSupplierOrdersOrderIdRoute
  '/supplier-orders/new': typeof AuthenticatedSupplierOrdersNewRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/supply-lots/$lotId': typeof AuthenticatedSupplyLotsLotIdRoute
  '/brands/': typeof AuthenticatedBrandsIndexRoute
  '/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/consignees/': typeof AuthenticatedConsigneesIndexRoute
  '/deliveries/': typeof AuthenticatedDeliveriesIndexRoute
  '/drive/': typeof AuthenticatedDriveIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/logistics/': typeof AuthenticatedLogisticsIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/purchase-intents/': typeof AuthenticatedPurchaseIntentsIndexRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/supplier-invoices/': typeof AuthenticatedSupplierInvoicesIndexRoute
  '/supplier-orders/': typeof AuthenticatedSupplierOrdersIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/supply-lots/': typeof AuthenticatedSupplyLotsIndexRoute
  '/warehouse/': typeof AuthenticatedWarehouseIndexRoute
  '/integrations/shopify/$storeId': typeof AuthenticatedIntegrationsShopifyStoreIdRoute
  '/integrations/x3/mappings': typeof AuthenticatedIntegrationsX3MappingsRoute
  '/settings/users/$userId': typeof AuthenticatedSettingsUsersUserIdRoute
  '/settings/users/new': typeof AuthenticatedSettingsUsersNewRoute
  '/warehouse/movements/$movementId': typeof AuthenticatedWarehouseMovementsMovementIdRoute
  '/warehouse/movements/new': typeof AuthenticatedWarehouseMovementsNewRoute
  '/accounting/aging/': typeof AuthenticatedAccountingAgingIndexRoute
  '/accounting/export/': typeof AuthenticatedAccountingExportIndexRoute
  '/accounting/payments/': typeof AuthenticatedAccountingPaymentsIndexRoute
  '/accounting/receivables/': typeof AuthenticatedAccountingReceivablesIndexRoute
  '/accounting/statements/': typeof AuthenticatedAccountingStatementsIndexRoute
  '/integrations/shopify/': typeof AuthenticatedIntegrationsShopifyIndexRoute
  '/settings/import/': typeof AuthenticatedSettingsImportIndexRoute
  '/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/warehouse/movements/': typeof AuthenticatedWarehouseMovementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/deliveries/$deliveryId': typeof AuthenticatedDeliveriesDeliveryIdRoute
  '/deliveries/new': typeof AuthenticatedDeliveriesNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/logistics/$shipmentId': typeof AuthenticatedLogisticsShipmentIdRoute
  '/logistics/new': typeof AuthenticatedLogisticsNewRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/purchase-intents/$intentId': typeof AuthenticatedPurchaseIntentsIntentIdRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/settings/email-logs': typeof AuthenticatedSettingsEmailLogsRoute
  '/supplier-invoices/$invoiceId': typeof AuthenticatedSupplierInvoicesInvoiceIdRoute
  '/supplier-invoices/new': typeof AuthenticatedSupplierInvoicesNewRoute
  '/supplier-orders/$orderId': typeof AuthenticatedSupplierOrdersOrderIdRoute
  '/supplier-orders/new': typeof AuthenticatedSupplierOrdersNewRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/supply-lots/$lotId': typeof AuthenticatedSupplyLotsLotIdRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/consignees': typeof AuthenticatedConsigneesIndexRoute
  '/deliveries': typeof AuthenticatedDeliveriesIndexRoute
  '/drive': typeof AuthenticatedDriveIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/logistics': typeof AuthenticatedLogisticsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/purchase-intents': typeof AuthenticatedPurchaseIntentsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/supplier-invoices': typeof AuthenticatedSupplierInvoicesIndexRoute
  '/supplier-orders': typeof AuthenticatedSupplierOrdersIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/supply-lots': typeof AuthenticatedSupplyLotsIndexRoute
  '/warehouse': typeof AuthenticatedWarehouseIndexRoute
  '/integrations/shopify/$storeId': typeof AuthenticatedIntegrationsShopifyStoreIdRoute
  '/integrations/x3/mappings': typeof AuthenticatedIntegrationsX3MappingsRoute
  '/settings/users/$userId': typeof AuthenticatedSettingsUsersUserIdRoute
  '/settings/users/new': typeof AuthenticatedSettingsUsersNewRoute
  '/warehouse/movements/$movementId': typeof AuthenticatedWarehouseMovementsMovementIdRoute
  '/warehouse/movements/new': typeof AuthenticatedWarehouseMovementsNewRoute
  '/accounting/aging': typeof AuthenticatedAccountingAgingIndexRoute
  '/accounting/export': typeof AuthenticatedAccountingExportIndexRoute
  '/accounting/payments': typeof AuthenticatedAccountingPaymentsIndexRoute
  '/accounting/receivables': typeof AuthenticatedAccountingReceivablesIndexRoute
  '/accounting/statements': typeof AuthenticatedAccountingStatementsIndexRoute
  '/integrations/shopify': typeof AuthenticatedIntegrationsShopifyIndexRoute
  '/settings/import': typeof AuthenticatedSettingsImportIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/warehouse/movements': typeof AuthenticatedWarehouseMovementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/deliveries/$deliveryId': typeof AuthenticatedDeliveriesDeliveryIdRoute
  '/_authenticated/deliveries/new': typeof AuthenticatedDeliveriesNewRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/logistics/$shipmentId': typeof AuthenticatedLogisticsShipmentIdRoute
  '/_authenticated/logistics/new': typeof AuthenticatedLogisticsNewRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/orders/new': typeof AuthenticatedOrdersNewRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/purchase-intents/$intentId': typeof AuthenticatedPurchaseIntentsIntentIdRoute
  '/_authenticated/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/_authenticated/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/settings/email-logs': typeof AuthenticatedSettingsEmailLogsRoute
  '/_authenticated/supplier-invoices/$invoiceId': typeof AuthenticatedSupplierInvoicesInvoiceIdRoute
  '/_authenticated/supplier-invoices/new': typeof AuthenticatedSupplierInvoicesNewRoute
  '/_authenticated/supplier-orders/$orderId': typeof AuthenticatedSupplierOrdersOrderIdRoute
  '/_authenticated/supplier-orders/new': typeof AuthenticatedSupplierOrdersNewRoute
  '/_authenticated/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRoute
  '/_authenticated/supply-lots/$lotId': typeof AuthenticatedSupplyLotsLotIdRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/consignees/': typeof AuthenticatedConsigneesIndexRoute
  '/_authenticated/deliveries/': typeof AuthenticatedDeliveriesIndexRoute
  '/_authenticated/drive/': typeof AuthenticatedDriveIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/logistics/': typeof AuthenticatedLogisticsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/purchase-intents/': typeof AuthenticatedPurchaseIntentsIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/supplier-invoices/': typeof AuthenticatedSupplierInvoicesIndexRoute
  '/_authenticated/supplier-orders/': typeof AuthenticatedSupplierOrdersIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/supply-lots/': typeof AuthenticatedSupplyLotsIndexRoute
  '/_authenticated/warehouse/': typeof AuthenticatedWarehouseIndexRoute
  '/_authenticated/integrations/shopify/$storeId': typeof AuthenticatedIntegrationsShopifyStoreIdRoute
  '/_authenticated/integrations/x3/mappings': typeof AuthenticatedIntegrationsX3MappingsRoute
  '/_authenticated/settings/users/$userId': typeof AuthenticatedSettingsUsersUserIdRoute
  '/_authenticated/settings/users/new': typeof AuthenticatedSettingsUsersNewRoute
  '/_authenticated/warehouse/movements/$movementId': typeof AuthenticatedWarehouseMovementsMovementIdRoute
  '/_authenticated/warehouse/movements/new': typeof AuthenticatedWarehouseMovementsNewRoute
  '/_authenticated/accounting/aging/': typeof AuthenticatedAccountingAgingIndexRoute
  '/_authenticated/accounting/export/': typeof AuthenticatedAccountingExportIndexRoute
  '/_authenticated/accounting/payments/': typeof AuthenticatedAccountingPaymentsIndexRoute
  '/_authenticated/accounting/receivables/': typeof AuthenticatedAccountingReceivablesIndexRoute
  '/_authenticated/accounting/statements/': typeof AuthenticatedAccountingStatementsIndexRoute
  '/_authenticated/integrations/shopify/': typeof AuthenticatedIntegrationsShopifyIndexRoute
  '/_authenticated/settings/import/': typeof AuthenticatedSettingsImportIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/_authenticated/warehouse/movements/': typeof AuthenticatedWarehouseMovementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/clients/$clientId'
    | '/deliveries/$deliveryId'
    | '/deliveries/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/logistics/$shipmentId'
    | '/logistics/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/products/$productId'
    | '/products/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/purchase-intents/$intentId'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/settings/email-logs'
    | '/supplier-invoices/$invoiceId'
    | '/supplier-invoices/new'
    | '/supplier-orders/$orderId'
    | '/supplier-orders/new'
    | '/suppliers/$supplierId'
    | '/supply-lots/$lotId'
    | '/brands/'
    | '/calendar/'
    | '/chat/'
    | '/clients/'
    | '/consignees/'
    | '/deliveries/'
    | '/drive/'
    | '/invoices/'
    | '/logistics/'
    | '/orders/'
    | '/products/'
    | '/projects/'
    | '/purchase-intents/'
    | '/quotes/'
    | '/supplier-invoices/'
    | '/supplier-orders/'
    | '/suppliers/'
    | '/supply-lots/'
    | '/warehouse/'
    | '/integrations/shopify/$storeId'
    | '/integrations/x3/mappings'
    | '/settings/users/$userId'
    | '/settings/users/new'
    | '/warehouse/movements/$movementId'
    | '/warehouse/movements/new'
    | '/accounting/aging/'
    | '/accounting/export/'
    | '/accounting/payments/'
    | '/accounting/receivables/'
    | '/accounting/statements/'
    | '/integrations/shopify/'
    | '/settings/import/'
    | '/settings/users/'
    | '/warehouse/movements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/clients/$clientId'
    | '/deliveries/$deliveryId'
    | '/deliveries/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/logistics/$shipmentId'
    | '/logistics/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/products/$productId'
    | '/products/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/purchase-intents/$intentId'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/settings/email-logs'
    | '/supplier-invoices/$invoiceId'
    | '/supplier-invoices/new'
    | '/supplier-orders/$orderId'
    | '/supplier-orders/new'
    | '/suppliers/$supplierId'
    | '/supply-lots/$lotId'
    | '/brands'
    | '/calendar'
    | '/chat'
    | '/clients'
    | '/consignees'
    | '/deliveries'
    | '/drive'
    | '/invoices'
    | '/logistics'
    | '/orders'
    | '/products'
    | '/projects'
    | '/purchase-intents'
    | '/quotes'
    | '/supplier-invoices'
    | '/supplier-orders'
    | '/suppliers'
    | '/supply-lots'
    | '/warehouse'
    | '/integrations/shopify/$storeId'
    | '/integrations/x3/mappings'
    | '/settings/users/$userId'
    | '/settings/users/new'
    | '/warehouse/movements/$movementId'
    | '/warehouse/movements/new'
    | '/accounting/aging'
    | '/accounting/export'
    | '/accounting/payments'
    | '/accounting/receivables'
    | '/accounting/statements'
    | '/integrations/shopify'
    | '/settings/import'
    | '/settings/users'
    | '/warehouse/movements'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/deliveries/$deliveryId'
    | '/_authenticated/deliveries/new'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/invoices/new'
    | '/_authenticated/logistics/$shipmentId'
    | '/_authenticated/logistics/new'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/orders/new'
    | '/_authenticated/products/$productId'
    | '/_authenticated/products/new'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/purchase-intents/$intentId'
    | '/_authenticated/quotes/$quoteId'
    | '/_authenticated/quotes/new'
    | '/_authenticated/settings/email-logs'
    | '/_authenticated/supplier-invoices/$invoiceId'
    | '/_authenticated/supplier-invoices/new'
    | '/_authenticated/supplier-orders/$orderId'
    | '/_authenticated/supplier-orders/new'
    | '/_authenticated/suppliers/$supplierId'
    | '/_authenticated/supply-lots/$lotId'
    | '/_authenticated/brands/'
    | '/_authenticated/calendar/'
    | '/_authenticated/chat/'
    | '/_authenticated/clients/'
    | '/_authenticated/consignees/'
    | '/_authenticated/deliveries/'
    | '/_authenticated/drive/'
    | '/_authenticated/invoices/'
    | '/_authenticated/logistics/'
    | '/_authenticated/orders/'
    | '/_authenticated/products/'
    | '/_authenticated/projects/'
    | '/_authenticated/purchase-intents/'
    | '/_authenticated/quotes/'
    | '/_authenticated/supplier-invoices/'
    | '/_authenticated/supplier-orders/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/supply-lots/'
    | '/_authenticated/warehouse/'
    | '/_authenticated/integrations/shopify/$storeId'
    | '/_authenticated/integrations/x3/mappings'
    | '/_authenticated/settings/users/$userId'
    | '/_authenticated/settings/users/new'
    | '/_authenticated/warehouse/movements/$movementId'
    | '/_authenticated/warehouse/movements/new'
    | '/_authenticated/accounting/aging/'
    | '/_authenticated/accounting/export/'
    | '/_authenticated/accounting/payments/'
    | '/_authenticated/accounting/receivables/'
    | '/_authenticated/accounting/statements/'
    | '/_authenticated/integrations/shopify/'
    | '/_authenticated/settings/import/'
    | '/_authenticated/settings/users/'
    | '/_authenticated/warehouse/movements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/': {
      id: '/_authenticated/warehouse/'
      path: '/warehouse'
      fullPath: '/warehouse/'
      preLoaderRoute: typeof AuthenticatedWarehouseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supply-lots/': {
      id: '/_authenticated/supply-lots/'
      path: '/supply-lots'
      fullPath: '/supply-lots/'
      preLoaderRoute: typeof AuthenticatedSupplyLotsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier-orders/': {
      id: '/_authenticated/supplier-orders/'
      path: '/supplier-orders'
      fullPath: '/supplier-orders/'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier-invoices/': {
      id: '/_authenticated/supplier-invoices/'
      path: '/supplier-invoices'
      fullPath: '/supplier-invoices/'
      preLoaderRoute: typeof AuthenticatedSupplierInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-intents/': {
      id: '/_authenticated/purchase-intents/'
      path: '/purchase-intents'
      fullPath: '/purchase-intents/'
      preLoaderRoute: typeof AuthenticatedPurchaseIntentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logistics/': {
      id: '/_authenticated/logistics/'
      path: '/logistics'
      fullPath: '/logistics/'
      preLoaderRoute: typeof AuthenticatedLogisticsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drive/': {
      id: '/_authenticated/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof AuthenticatedDriveIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries/': {
      id: '/_authenticated/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof AuthenticatedDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consignees/': {
      id: '/_authenticated/consignees/'
      path: '/consignees'
      fullPath: '/consignees/'
      preLoaderRoute: typeof AuthenticatedConsigneesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AuthenticatedBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supply-lots/$lotId': {
      id: '/_authenticated/supply-lots/$lotId'
      path: '/supply-lots/$lotId'
      fullPath: '/supply-lots/$lotId'
      preLoaderRoute: typeof AuthenticatedSupplyLotsLotIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/$supplierId': {
      id: '/_authenticated/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier-orders/new': {
      id: '/_authenticated/supplier-orders/new'
      path: '/supplier-orders/new'
      fullPath: '/supplier-orders/new'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier-orders/$orderId': {
      id: '/_authenticated/supplier-orders/$orderId'
      path: '/supplier-orders/$orderId'
      fullPath: '/supplier-orders/$orderId'
      preLoaderRoute: typeof AuthenticatedSupplierOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier-invoices/new': {
      id: '/_authenticated/supplier-invoices/new'
      path: '/supplier-invoices/new'
      fullPath: '/supplier-invoices/new'
      preLoaderRoute: typeof AuthenticatedSupplierInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier-invoices/$invoiceId': {
      id: '/_authenticated/supplier-invoices/$invoiceId'
      path: '/supplier-invoices/$invoiceId'
      fullPath: '/supplier-invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedSupplierInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/email-logs': {
      id: '/_authenticated/settings/email-logs'
      path: '/settings/email-logs'
      fullPath: '/settings/email-logs'
      preLoaderRoute: typeof AuthenticatedSettingsEmailLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes/new': {
      id: '/_authenticated/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes/$quoteId': {
      id: '/_authenticated/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-intents/$intentId': {
      id: '/_authenticated/purchase-intents/$intentId'
      path: '/purchase-intents/$intentId'
      fullPath: '/purchase-intents/$intentId'
      preLoaderRoute: typeof AuthenticatedPurchaseIntentsIntentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/new': {
      id: '/_authenticated/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logistics/new': {
      id: '/_authenticated/logistics/new'
      path: '/logistics/new'
      fullPath: '/logistics/new'
      preLoaderRoute: typeof AuthenticatedLogisticsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logistics/$shipmentId': {
      id: '/_authenticated/logistics/$shipmentId'
      path: '/logistics/$shipmentId'
      fullPath: '/logistics/$shipmentId'
      preLoaderRoute: typeof AuthenticatedLogisticsShipmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries/new': {
      id: '/_authenticated/deliveries/new'
      path: '/deliveries/new'
      fullPath: '/deliveries/new'
      preLoaderRoute: typeof AuthenticatedDeliveriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries/$deliveryId': {
      id: '/_authenticated/deliveries/$deliveryId'
      path: '/deliveries/$deliveryId'
      fullPath: '/deliveries/$deliveryId'
      preLoaderRoute: typeof AuthenticatedDeliveriesDeliveryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/movements/': {
      id: '/_authenticated/warehouse/movements/'
      path: '/warehouse/movements'
      fullPath: '/warehouse/movements/'
      preLoaderRoute: typeof AuthenticatedWarehouseMovementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/settings/users'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/import/': {
      id: '/_authenticated/settings/import/'
      path: '/settings/import'
      fullPath: '/settings/import/'
      preLoaderRoute: typeof AuthenticatedSettingsImportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/shopify/': {
      id: '/_authenticated/integrations/shopify/'
      path: '/integrations/shopify'
      fullPath: '/integrations/shopify/'
      preLoaderRoute: typeof AuthenticatedIntegrationsShopifyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/statements/': {
      id: '/_authenticated/accounting/statements/'
      path: '/accounting/statements'
      fullPath: '/accounting/statements/'
      preLoaderRoute: typeof AuthenticatedAccountingStatementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/receivables/': {
      id: '/_authenticated/accounting/receivables/'
      path: '/accounting/receivables'
      fullPath: '/accounting/receivables/'
      preLoaderRoute: typeof AuthenticatedAccountingReceivablesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/payments/': {
      id: '/_authenticated/accounting/payments/'
      path: '/accounting/payments'
      fullPath: '/accounting/payments/'
      preLoaderRoute: typeof AuthenticatedAccountingPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/export/': {
      id: '/_authenticated/accounting/export/'
      path: '/accounting/export'
      fullPath: '/accounting/export/'
      preLoaderRoute: typeof AuthenticatedAccountingExportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/aging/': {
      id: '/_authenticated/accounting/aging/'
      path: '/accounting/aging'
      fullPath: '/accounting/aging/'
      preLoaderRoute: typeof AuthenticatedAccountingAgingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/movements/new': {
      id: '/_authenticated/warehouse/movements/new'
      path: '/warehouse/movements/new'
      fullPath: '/warehouse/movements/new'
      preLoaderRoute: typeof AuthenticatedWarehouseMovementsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouse/movements/$movementId': {
      id: '/_authenticated/warehouse/movements/$movementId'
      path: '/warehouse/movements/$movementId'
      fullPath: '/warehouse/movements/$movementId'
      preLoaderRoute: typeof AuthenticatedWarehouseMovementsMovementIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users/new': {
      id: '/_authenticated/settings/users/new'
      path: '/settings/users/new'
      fullPath: '/settings/users/new'
      preLoaderRoute: typeof AuthenticatedSettingsUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users/$userId': {
      id: '/_authenticated/settings/users/$userId'
      path: '/settings/users/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof AuthenticatedSettingsUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/x3/mappings': {
      id: '/_authenticated/integrations/x3/mappings'
      path: '/integrations/x3/mappings'
      fullPath: '/integrations/x3/mappings'
      preLoaderRoute: typeof AuthenticatedIntegrationsX3MappingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/shopify/$storeId': {
      id: '/_authenticated/integrations/shopify/$storeId'
      path: '/integrations/shopify/$storeId'
      fullPath: '/integrations/shopify/$storeId'
      preLoaderRoute: typeof AuthenticatedIntegrationsShopifyStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedDeliveriesDeliveryIdRoute: typeof AuthenticatedDeliveriesDeliveryIdRoute
  AuthenticatedDeliveriesNewRoute: typeof AuthenticatedDeliveriesNewRoute
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedLogisticsShipmentIdRoute: typeof AuthenticatedLogisticsShipmentIdRoute
  AuthenticatedLogisticsNewRoute: typeof AuthenticatedLogisticsNewRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedOrdersNewRoute: typeof AuthenticatedOrdersNewRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedPurchaseIntentsIntentIdRoute: typeof AuthenticatedPurchaseIntentsIntentIdRoute
  AuthenticatedQuotesQuoteIdRoute: typeof AuthenticatedQuotesQuoteIdRoute
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
  AuthenticatedSettingsEmailLogsRoute: typeof AuthenticatedSettingsEmailLogsRoute
  AuthenticatedSupplierInvoicesInvoiceIdRoute: typeof AuthenticatedSupplierInvoicesInvoiceIdRoute
  AuthenticatedSupplierInvoicesNewRoute: typeof AuthenticatedSupplierInvoicesNewRoute
  AuthenticatedSupplierOrdersOrderIdRoute: typeof AuthenticatedSupplierOrdersOrderIdRoute
  AuthenticatedSupplierOrdersNewRoute: typeof AuthenticatedSupplierOrdersNewRoute
  AuthenticatedSuppliersSupplierIdRoute: typeof AuthenticatedSuppliersSupplierIdRoute
  AuthenticatedSupplyLotsLotIdRoute: typeof AuthenticatedSupplyLotsLotIdRoute
  AuthenticatedBrandsIndexRoute: typeof AuthenticatedBrandsIndexRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedConsigneesIndexRoute: typeof AuthenticatedConsigneesIndexRoute
  AuthenticatedDeliveriesIndexRoute: typeof AuthenticatedDeliveriesIndexRoute
  AuthenticatedDriveIndexRoute: typeof AuthenticatedDriveIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedLogisticsIndexRoute: typeof AuthenticatedLogisticsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedPurchaseIntentsIndexRoute: typeof AuthenticatedPurchaseIntentsIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
  AuthenticatedSupplierInvoicesIndexRoute: typeof AuthenticatedSupplierInvoicesIndexRoute
  AuthenticatedSupplierOrdersIndexRoute: typeof AuthenticatedSupplierOrdersIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedSupplyLotsIndexRoute: typeof AuthenticatedSupplyLotsIndexRoute
  AuthenticatedWarehouseIndexRoute: typeof AuthenticatedWarehouseIndexRoute
  AuthenticatedIntegrationsShopifyStoreIdRoute: typeof AuthenticatedIntegrationsShopifyStoreIdRoute
  AuthenticatedIntegrationsX3MappingsRoute: typeof AuthenticatedIntegrationsX3MappingsRoute
  AuthenticatedSettingsUsersUserIdRoute: typeof AuthenticatedSettingsUsersUserIdRoute
  AuthenticatedSettingsUsersNewRoute: typeof AuthenticatedSettingsUsersNewRoute
  AuthenticatedWarehouseMovementsMovementIdRoute: typeof AuthenticatedWarehouseMovementsMovementIdRoute
  AuthenticatedWarehouseMovementsNewRoute: typeof AuthenticatedWarehouseMovementsNewRoute
  AuthenticatedAccountingAgingIndexRoute: typeof AuthenticatedAccountingAgingIndexRoute
  AuthenticatedAccountingExportIndexRoute: typeof AuthenticatedAccountingExportIndexRoute
  AuthenticatedAccountingPaymentsIndexRoute: typeof AuthenticatedAccountingPaymentsIndexRoute
  AuthenticatedAccountingReceivablesIndexRoute: typeof AuthenticatedAccountingReceivablesIndexRoute
  AuthenticatedAccountingStatementsIndexRoute: typeof AuthenticatedAccountingStatementsIndexRoute
  AuthenticatedIntegrationsShopifyIndexRoute: typeof AuthenticatedIntegrationsShopifyIndexRoute
  AuthenticatedSettingsImportIndexRoute: typeof AuthenticatedSettingsImportIndexRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
  AuthenticatedWarehouseMovementsIndexRoute: typeof AuthenticatedWarehouseMovementsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedDeliveriesDeliveryIdRoute:
    AuthenticatedDeliveriesDeliveryIdRoute,
  AuthenticatedDeliveriesNewRoute: AuthenticatedDeliveriesNewRoute,
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedLogisticsShipmentIdRoute: AuthenticatedLogisticsShipmentIdRoute,
  AuthenticatedLogisticsNewRoute: AuthenticatedLogisticsNewRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedOrdersNewRoute: AuthenticatedOrdersNewRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedPurchaseIntentsIntentIdRoute:
    AuthenticatedPurchaseIntentsIntentIdRoute,
  AuthenticatedQuotesQuoteIdRoute: AuthenticatedQuotesQuoteIdRoute,
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
  AuthenticatedSettingsEmailLogsRoute: AuthenticatedSettingsEmailLogsRoute,
  AuthenticatedSupplierInvoicesInvoiceIdRoute:
    AuthenticatedSupplierInvoicesInvoiceIdRoute,
  AuthenticatedSupplierInvoicesNewRoute: AuthenticatedSupplierInvoicesNewRoute,
  AuthenticatedSupplierOrdersOrderIdRoute:
    AuthenticatedSupplierOrdersOrderIdRoute,
  AuthenticatedSupplierOrdersNewRoute: AuthenticatedSupplierOrdersNewRoute,
  AuthenticatedSuppliersSupplierIdRoute: AuthenticatedSuppliersSupplierIdRoute,
  AuthenticatedSupplyLotsLotIdRoute: AuthenticatedSupplyLotsLotIdRoute,
  AuthenticatedBrandsIndexRoute: AuthenticatedBrandsIndexRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedConsigneesIndexRoute: AuthenticatedConsigneesIndexRoute,
  AuthenticatedDeliveriesIndexRoute: AuthenticatedDeliveriesIndexRoute,
  AuthenticatedDriveIndexRoute: AuthenticatedDriveIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedLogisticsIndexRoute: AuthenticatedLogisticsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedPurchaseIntentsIndexRoute:
    AuthenticatedPurchaseIntentsIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
  AuthenticatedSupplierInvoicesIndexRoute:
    AuthenticatedSupplierInvoicesIndexRoute,
  AuthenticatedSupplierOrdersIndexRoute: AuthenticatedSupplierOrdersIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedSupplyLotsIndexRoute: AuthenticatedSupplyLotsIndexRoute,
  AuthenticatedWarehouseIndexRoute: AuthenticatedWarehouseIndexRoute,
  AuthenticatedIntegrationsShopifyStoreIdRoute:
    AuthenticatedIntegrationsShopifyStoreIdRoute,
  AuthenticatedIntegrationsX3MappingsRoute:
    AuthenticatedIntegrationsX3MappingsRoute,
  AuthenticatedSettingsUsersUserIdRoute: AuthenticatedSettingsUsersUserIdRoute,
  AuthenticatedSettingsUsersNewRoute: AuthenticatedSettingsUsersNewRoute,
  AuthenticatedWarehouseMovementsMovementIdRoute:
    AuthenticatedWarehouseMovementsMovementIdRoute,
  AuthenticatedWarehouseMovementsNewRoute:
    AuthenticatedWarehouseMovementsNewRoute,
  AuthenticatedAccountingAgingIndexRoute:
    AuthenticatedAccountingAgingIndexRoute,
  AuthenticatedAccountingExportIndexRoute:
    AuthenticatedAccountingExportIndexRoute,
  AuthenticatedAccountingPaymentsIndexRoute:
    AuthenticatedAccountingPaymentsIndexRoute,
  AuthenticatedAccountingReceivablesIndexRoute:
    AuthenticatedAccountingReceivablesIndexRoute,
  AuthenticatedAccountingStatementsIndexRoute:
    AuthenticatedAccountingStatementsIndexRoute,
  AuthenticatedIntegrationsShopifyIndexRoute:
    AuthenticatedIntegrationsShopifyIndexRoute,
  AuthenticatedSettingsImportIndexRoute: AuthenticatedSettingsImportIndexRoute,
  AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
  AuthenticatedWarehouseMovementsIndexRoute:
    AuthenticatedWarehouseMovementsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
